
@startuml
title Colaboracion - Iteracion 2
left to right direction

object "persona:Persona" as P
object "accion:Accion" as A
object "contexto:Contexto" as C
object "observador:Observador" as O
object "aura:Aura" as U

P --> A : 1: realizar accion
A --> C : 2: ocurrir en un contexto
A --> O : 3: ser observada
O --> U : 4: influir en el aura

@enduml
