
@startuml
title Estados - Iteracion 2

state "Aura neutra" as Neutra
state "Aura elevada" as Elevada
state "Aura reducida" as Reducida

[*] --> Neutra

Neutra --> Elevada : Valoracion positiva
Neutra --> Reducida : Valoracion negativa

@enduml
