
@startuml
title Estados - Iteracion 3

state "Aura neutra" as Neutra
state "Aura elevada" as Elevada
state "Aura reducida" as Reducida

[*] --> Neutra

Neutra --> Elevada : Valoracion positiva
Neutra --> Reducida : Valoracion negativa

Elevada --> Neutra : Disminuye la admiracion
Reducida --> Neutra : Mejora la percepcion

@enduml

